// АВТОГЕНЕРАЦИЯ — не редактировать вручную.
// Источник: https://t.me/s/masloplus. Обновляется скриптом scripts/fetch-telegram.mjs
// (локально: npm run fetch:telegram; на CI: .github/workflows/telegram.yml).
import type { GalleryVideo } from "@/types/gallery";

/** Последние видео из Telegram-канала, свежие — сверху. */
export const telegramGallery: GalleryVideo[] = [
  {
    id: "tg-2776",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2776" },
    thumb: "/gallery/telegram/2776.jpg",
    title: "BMW X6 — меняем масло в двигателе и в АКПП вместе с поддоном. 🔧",
    caption: "BMW X6 — меняем масло в двигателе и в АКПП вместе с поддоном. 🔧 Мотор скажет спасибо за свежее масло, а коробка — за плавные переключения. ⚙️ Нужен уход для в…",
    publishedAt: "2026-09-25T12:14:27+00:00",
    sourceUrl: "https://t.me/masloplus/2776",
  },
  {
    id: "tg-2775",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2775" },
    thumb: "/gallery/telegram/2775.jpg",
    title: "Ура, посылка разгружена! 📦✨",
    caption: "Ура, посылка разгружена! 📦✨ Совсем скоро — распаковка, вас ждёт приятный бонус 👀 Следите за новостями, чтобы не пропустить 😉",
    publishedAt: "2026-09-25T10:55:11+00:00",
    sourceUrl: "https://t.me/masloplus/2775",
  },
  {
    id: "tg-2774",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2774" },
    thumb: "/gallery/telegram/2774.jpg",
    title: "🔧 Запчасти и ремонт — в одном месте.",
    caption: "🔧 Запчасти и ремонт — в одном месте. Не тратьте время на поиски. Всё нужное есть у нас, мастера приступят сразу. Доставка в течение часа. Быстро и без лишних…",
    publishedAt: "2026-09-22T06:56:08+00:00",
    sourceUrl: "https://t.me/masloplus/2774",
  },
  {
    id: "tg-2773",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2773" },
    thumb: "/gallery/telegram/2773.jpg",
    title: "⛽️ 95-й бензин найти всё сложнее. Но лить сомнительное топливо — прямой риск дл…",
    caption: "⛽️ 95-й бензин найти всё сложнее. Но лить сомнительное топливо — прямой риск для двигателя. Помощник — топливная присадка. Она корректирует октановое число и к…",
    publishedAt: "2026-09-21T19:36:17+00:00",
    sourceUrl: "https://t.me/masloplus/2773",
  },
  {
    id: "tg-2771",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2771" },
    thumb: "/gallery/telegram/2771.jpg",
    title: "⚠️ Проверяйте уровень масла в АКПП сразу после покупки нового китайского автомо…",
    caption: "⚠️ Проверяйте уровень масла в АКПП сразу после покупки нового китайского автомобиля. По статистике, около 70% таких машин приходят с завода с недолитым маслом…",
    publishedAt: "2026-09-21T17:20:59+00:00",
    sourceUrl: "https://t.me/masloplus/2771",
  },
  {
    id: "tg-2768",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2768" },
    thumb: "/gallery/telegram/2768.jpg",
    title: "Обратите внимание на цвет при сливе: отработанное масло чернющее ⚫️",
    caption: "Обратите внимание на цвет при сливе: отработанное масло чернющее ⚫️ Новое DCTFE идёт жёлтым, светлым. 🟡 По цвету судят о состоянии жидкости, но решение о заме…",
    publishedAt: "2026-09-21T16:44:48+00:00",
    sourceUrl: "https://t.me/masloplus/2768",
  },
  {
    id: "tg-2767",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2767" },
    thumb: "/gallery/telegram/2767.jpg",
    title: "Chery Tiggo 8 Pro, 6-ступенчатый автомат — на обслуживании заливаем Лукойл DCTF…",
    caption: "Chery Tiggo 8 Pro, 6-ступенчатый автомат — на обслуживании заливаем Лукойл DCTFE, ту же жидкость, что с завода. ⚙️",
    publishedAt: "2026-09-21T16:35:45+00:00",
    sourceUrl: "https://t.me/masloplus/2767",
  },
  {
    id: "tg-2766",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2766" },
    thumb: "/gallery/telegram/2766.jpg",
    title: "🔧 Запчасти и ремонт — в одном месте.",
    caption: "🔧 Запчасти и ремонт — в одном месте. Не тратьте время на поиски. Всё нужное есть у нас, мастера приступят сразу. Доставка в течение часа. Быстро и без лишних…",
    publishedAt: "2026-09-21T15:29:02+00:00",
    sourceUrl: "https://t.me/masloplus/2766",
  },
  {
    id: "tg-2762",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2762" },
    thumb: "/gallery/telegram/2762.jpg",
    title: "🔥 Долгожданная поставка присадки для дизеля и бензина — прямо из Германии.",
    caption: "🔥 Долгожданная поставка присадки для дизеля и бензина — прямо из Германии. Защитит ваш двигатель и топливную систему. Особенно актуально на фоне ситуации с то…",
    publishedAt: "2026-09-21T06:54:58+00:00",
    sourceUrl: "https://t.me/masloplus/2762",
  },
  {
    id: "tg-2761",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2761" },
    thumb: "/gallery/telegram/2761.jpg",
    title: "⛽️ Ситуация с топливом диктует новые правила ухода за авто.",
    caption: "⛽️ Ситуация с топливом диктует новые правила ухода за авто. Вот что действительно имеет смысл делать: 🔧 Масло — чаще. Некачественное топливо ускоряет деградац…",
    publishedAt: "2026-09-21T06:40:51+00:00",
    sourceUrl: "https://t.me/masloplus/2761",
  },
  {
    id: "tg-2760",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2760" },
    thumb: "/gallery/telegram/2760.jpg",
    title: "☀️ Доброе утро! Пусть неделя будет лёгкой и продуктивной, а ваша машина — надёж…",
    caption: "☀️ Доброе утро! Пусть неделя будет лёгкой и продуктивной, а ваша машина — надёжной и безотказной. А если что — мы рядом и всегда поможем. 📍 Адреса: 👨‍🔧 ул.…",
    publishedAt: "2026-09-21T06:10:54+00:00",
    sourceUrl: "https://t.me/masloplus/2760",
  },
  {
    id: "tg-2759",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2759" },
    thumb: "/gallery/telegram/2759.jpg",
    title: "Забота об автомобиле начинается с внимания к деталям, которые незаметны снаружи…",
    caption: "Забота об автомобиле начинается с внимания к деталям, которые незаметны снаружи, но определяют его надёжность изнутри. Своевременная замена масла в АКПП с подд…",
    publishedAt: "2026-09-18T18:21:05+00:00",
    sourceUrl: "https://t.me/masloplus/2759",
  },
  {
    id: "tg-2758",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2758" },
    thumb: "/gallery/telegram/2758.jpg",
    title: "🔧 Замена масла в АКПП Genesis G90 со снятием поддона",
    caption: "🔧 Замена масла в АКПП Genesis G90 со снятием поддона Слив через пробку — это лишь треть работы. Реальный результат даёт только полный цикл. Порядок работ: 1️⃣…",
    publishedAt: "2026-09-18T15:57:13+00:00",
    sourceUrl: "https://t.me/masloplus/2758",
  },
  {
    id: "tg-2757",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2757" },
    thumb: "/gallery/telegram/2757.jpg",
    title: "Красив красив 🖤",
    caption: "Красив красив 🖤",
    publishedAt: "2026-09-18T15:45:11+00:00",
    sourceUrl: "https://t.me/masloplus/2757",
  },
  {
    id: "tg-2754",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2754" },
    thumb: "/gallery/telegram/2754.jpg",
    title: "Новое поступление для Ford и GM. 🚗",
    caption: "Новое поступление для Ford и GM. 🚗 Ford 5W30 Допуски: ACEA A5/B5, Ford WSS-M2C 913-A, 913-B, 913-C. ✅ GM 5W30 Допуски: GM-LL-A-025, GM-LL-B-025, VW 502.00/505…",
    publishedAt: "2026-09-18T11:00:52+00:00",
    sourceUrl: "https://t.me/masloplus/2754",
  },
];
