// АВТОГЕНЕРАЦИЯ — не редактировать вручную.
// Источник: https://t.me/s/masloplus. Обновляется скриптом scripts/fetch-telegram.mjs
// (локально: npm run fetch:telegram; на CI: .github/workflows/telegram.yml).
import type { GalleryVideo } from "@/types/gallery";

/** Последние видео из Telegram-канала, свежие — сверху. */
export const telegramGallery: GalleryVideo[] = [
  {
    id: "tg-2820",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2820" },
    thumb: "/gallery/telegram/2820.jpg",
    title: "🔧 Lada Granta, 56 000 км — замена ремня ГРМ.",
    caption: "🔧 Lada Granta, 56 000 км — замена ремня ГРМ. Ремень снят. Оцените износ: трещины, растяжение, выработка зубьев — прямой путь к обрыву. ⚠️ На Granta обрыв гроз…",
    publishedAt: "2026-10-05T10:35:44+00:00",
    sourceUrl: "https://t.me/masloplus/2820",
  },
  {
    id: "tg-2818",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2818" },
    thumb: "/gallery/telegram/2818.jpg",
    title: "🔧 В работе",
    caption: "🔧 В работе 🚗 Lada Granta, 56 000 км — замена ремня ГРМ. Критичный пробег: обрыв грозит капремонтом двигателя. ⚙️ Kia Sportage — частичная замена масла в АКПП…",
    publishedAt: "2026-10-05T08:07:37+00:00",
    sourceUrl: "https://t.me/masloplus/2818",
  },
  {
    id: "tg-2817",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2817" },
    thumb: "/gallery/telegram/2817.jpg",
    title: "🌅 Доброе утро понедельника!",
    caption: "🌅 Доброе утро понедельника! Пусть неделя будет лёгкой, а планы — выполнимыми. Желаем, чтобы ваш железный друг — автомобиль — всегда заводился с полуоборота и…",
    publishedAt: "2026-10-05T07:19:53+00:00",
    sourceUrl: "https://t.me/masloplus/2817",
  },
  {
    id: "tg-2814",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2814" },
    thumb: "/gallery/telegram/2814.jpg",
    title: "Муфта Haldex",
    caption: "Муфта Haldex Состояние её масла и насоса 🤨⚫️",
    publishedAt: "2026-10-04T08:02:10+00:00",
    sourceUrl: "https://t.me/masloplus/2814",
  },
  {
    id: "tg-2811",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2811" },
    thumb: "/gallery/telegram/2811.jpg",
    title: "🔧 Chery Tiggo 7 Pro Max — замена масла в редукторе и муфте Haldex",
    caption: "🔧 Chery Tiggo 7 Pro Max — замена масла в редукторе и муфте Haldex Пробег 66 000 км. Из муфты Haldex слилось всего 100 грамм масла. ⚠️ Это в разы меньше нормы…",
    publishedAt: "2026-10-04T08:00:14+00:00",
    sourceUrl: "https://t.me/masloplus/2811",
  },
  {
    id: "tg-2810",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2810" },
    thumb: "/gallery/telegram/2810.jpg",
    title: "Работаем 7/7, в выходные — с 9:00 до 17:00. 🕘",
    caption: "Работаем 7/7, в выходные — с 9:00 до 17:00. 🕘 📍 ул. Б. Хмельницкого, 73 — 386-383 📍 ул. Л. Комсомола, 29 — 24-24-11 📍 Университетская, 35А — 21-22-88 Обращ…",
    publishedAt: "2026-10-04T06:31:05+00:00",
    sourceUrl: "https://t.me/masloplus/2810",
  },
  {
    id: "tg-2809",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2809" },
    thumb: "/gallery/telegram/2809.jpg",
    title: "🚗 Работаем 7/7.",
    caption: "🚗 Работаем 7/7. Выходные — самое время заняться авто. На подъёмнике Kia Rio: замена масла в двигателе, воздушного и салонного фильтров. На втором подъёмнике H…",
    publishedAt: "2026-10-03T13:10:13+00:00",
    sourceUrl: "https://t.me/masloplus/2809",
  },
  {
    id: "tg-2808",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2808" },
    thumb: "/gallery/telegram/2808.jpg",
    title: "📍Точка СЗР",
    caption: "📍Точка СЗР 📍 Адрес:Университетская 35А 📞 Телефон: 21-22-88 (звоните, записывайтесь) 📩 Написать нам в Telegram 📝 Записаться на обслуживание",
    publishedAt: "2026-10-03T10:31:27+00:00",
    sourceUrl: "https://t.me/masloplus/2808",
  },
  {
    id: "tg-2807",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2807" },
    thumb: "/gallery/telegram/2807.jpg",
    title: "📍Точка Новоюжка",
    caption: "📍Точка Новоюжка 📍 Адрес: ул. Ленинского Комсомола , 29 📞 Телефон: 24-24-11 (звоните, записывайтесь) 📩 Написать нам в Telegram 📝 Записаться на обслуживание",
    publishedAt: "2026-10-03T10:25:36+00:00",
    sourceUrl: "https://t.me/masloplus/2807",
  },
  {
    id: "tg-2806",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2806" },
    thumb: "/gallery/telegram/2806.jpg",
    title: "📍Точка Богданка",
    caption: "📍Точка Богданка 📍 Адрес: ул. Богдана Хмельницкого, 73 📞 Телефон: 386-383 (звоните, записывайтесь) 📩 Написать нам в Telegram 📝 Записаться на обслуживание",
    publishedAt: "2026-10-03T10:20:06+00:00",
    sourceUrl: "https://t.me/masloplus/2806",
  },
  {
    id: "tg-2803",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2803" },
    thumb: "/gallery/telegram/2803.jpg",
    title: "🔧 Красавец 😍заезжал на вибростенд — BMW X6 2024 , G06.",
    caption: "🔧 Красавец 😍заезжал на вибростенд — BMW X6 2024 , G06. В ходе диагностики выявили проблему: рулевые тяги под замену. Клиент долго не мог найти причину. Вибро…",
    publishedAt: "2026-10-02T16:22:34+00:00",
    sourceUrl: "https://t.me/masloplus/2803",
  },
];
