// АВТОГЕНЕРАЦИЯ — не редактировать вручную.
// Источник: https://t.me/s/masloplus. Обновляется скриптом scripts/fetch-telegram.mjs
// (локально: npm run fetch:telegram; на CI: .github/workflows/telegram.yml).
import type { GalleryVideo } from "@/types/gallery";

/** Последние видео из Telegram-канала, свежие — сверху. */
export const telegramGallery: GalleryVideo[] = [
  {
    id: "tg-2762",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2762" },
    thumb: "/gallery/telegram/2762.jpg",
    title: "🔥 Долгожданная поставка присадки для дизеля и бензина — прямо из Германии.",
    caption: "🔥 Долгожданная поставка присадки для дизеля и бензина — прямо из Германии. Защитит ваш двигатель и топливную систему. Особенно актуально на фоне ситуации с то…",
    publishedAt: "2026-09-21T06:54:58+00:00",
    sourceUrl: "https://t.me/masloplus/2762",
  },
  {
    id: "tg-2761",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2761" },
    thumb: "/gallery/telegram/2761.jpg",
    title: "⛽️ Ситуация с топливом диктует новые правила ухода за авто.",
    caption: "⛽️ Ситуация с топливом диктует новые правила ухода за авто. Вот что действительно имеет смысл делать: 🔧 Масло — чаще. Некачественное топливо ускоряет деградац…",
    publishedAt: "2026-09-21T06:40:51+00:00",
    sourceUrl: "https://t.me/masloplus/2761",
  },
  {
    id: "tg-2760",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2760" },
    thumb: "/gallery/telegram/2760.jpg",
    title: "☀️ Доброе утро! Пусть неделя будет лёгкой и продуктивной, а ваша машина — надёж…",
    caption: "☀️ Доброе утро! Пусть неделя будет лёгкой и продуктивной, а ваша машина — надёжной и безотказной. А если что — мы рядом и всегда поможем. 📍 Адреса: 👨‍🔧 ул.…",
    publishedAt: "2026-09-21T06:10:54+00:00",
    sourceUrl: "https://t.me/masloplus/2760",
  },
  {
    id: "tg-2759",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2759" },
    thumb: "/gallery/telegram/2759.jpg",
    title: "Забота об автомобиле начинается с внимания к деталям, которые незаметны снаружи…",
    caption: "Забота об автомобиле начинается с внимания к деталям, которые незаметны снаружи, но определяют его надёжность изнутри. Своевременная замена масла в АКПП с подд…",
    publishedAt: "2026-09-18T18:21:05+00:00",
    sourceUrl: "https://t.me/masloplus/2759",
  },
  {
    id: "tg-2758",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2758" },
    thumb: "/gallery/telegram/2758.jpg",
    title: "🔧 Замена масла в АКПП Genesis G90 со снятием поддона",
    caption: "🔧 Замена масла в АКПП Genesis G90 со снятием поддона Слив через пробку — это лишь треть работы. Реальный результат даёт только полный цикл. Порядок работ: 1️⃣…",
    publishedAt: "2026-09-18T15:57:13+00:00",
    sourceUrl: "https://t.me/masloplus/2758",
  },
  {
    id: "tg-2757",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2757" },
    thumb: "/gallery/telegram/2757.jpg",
    title: "Красив красив 🖤",
    caption: "Красив красив 🖤",
    publishedAt: "2026-09-18T15:45:11+00:00",
    sourceUrl: "https://t.me/masloplus/2757",
  },
  {
    id: "tg-2754",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2754" },
    thumb: "/gallery/telegram/2754.jpg",
    title: "Новое поступление для Ford и GM. 🚗",
    caption: "Новое поступление для Ford и GM. 🚗 Ford 5W30 Допуски: ACEA A5/B5, Ford WSS-M2C 913-A, 913-B, 913-C. ✅ GM 5W30 Допуски: GM-LL-A-025, GM-LL-B-025, VW 502.00/505…",
    publishedAt: "2026-09-18T11:00:52+00:00",
    sourceUrl: "https://t.me/masloplus/2754",
  },
  {
    id: "tg-2753",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2753" },
    thumb: "/gallery/telegram/2753.jpg",
    title: "Привет! 👋",
    caption: "Привет! 👋 Работаем — приезжай, подберём масло под твой двигатель и заправим как надо. 🛠️ Ждём!",
    publishedAt: "2026-09-18T09:15:44+00:00",
    sourceUrl: "https://t.me/masloplus/2753",
  },
  {
    id: "tg-2752",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2752" },
    thumb: "/gallery/telegram/2752.jpg",
    title: "🔥 Новое поступление — японское масло",
    caption: "🔥 Новое поступление — японское масло IDEMITSU ZEPRO 0W-20 Полностью синтетическое масло для современных бензиновых двигателей. 📋 Допуски: • API SP • ILSAC GF…",
    publishedAt: "2026-09-17T12:42:34+00:00",
    sourceUrl: "https://t.me/masloplus/2752",
  },
  {
    id: "tg-2751",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2751" },
    thumb: "/gallery/telegram/2751.jpg",
    title: "Сделано с любовью к твоему авто ❤️",
    caption: "Сделано с любовью к твоему авто ❤️ Каждое масло, запчасть и обслуживание — подобраны с заботой 🔧 Заезжай в гости 🚗",
    publishedAt: "2026-09-17T06:06:57+00:00",
    sourceUrl: "https://t.me/masloplus/2751",
  },
  {
    id: "tg-2747",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2747" },
    thumb: "/gallery/telegram/2747.jpg",
    title: "🔧 Geely Monjaro: замена масла в 8-ступенчатой АКПП",
    caption: "🔧 Geely Monjaro: замена масла в 8-ступенчатой АКПП Наглядно показываем состояние масла: цвет, запах, взвесь и продукты износа. По ним видно реальную нагрузку…",
    publishedAt: "2026-09-15T13:24:09+00:00",
    sourceUrl: "https://t.me/masloplus/2747",
  },
  {
    id: "tg-2746",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2746" },
    thumb: "/gallery/telegram/2746.jpg",
    title: "📍Точка Богданка",
    caption: "📍Точка Богданка 📍 Адрес: ул. Богдана Хмельницкого, 73 📞 Телефон: 386-383 (звоните, записывайтесь) 📩 Написать нам в Telegram 📝 Записаться на обслуживание",
    publishedAt: "2026-09-15T08:37:01+00:00",
    sourceUrl: "https://t.me/masloplus/2746",
  },
  {
    id: "tg-2742",
    type: "video",
    video: { provider: "telegram", channel: "masloplus", id: "2742" },
    thumb: "/gallery/telegram/2742.jpg",
    title: "🚗 Mini Cooper 2022, 1.4, 136 л.с., пробег 47 000 км.",
    caption: "🚗 Mini Cooper 2022, 1.4, 136 л.с., пробег 47 000 км. Под капотом — BMW. Залито Jetout 5W-30 с допуском BMW Longlife-04. ✅ Допуск подобран верно: защита турбин…",
    publishedAt: "2026-09-15T08:20:28+00:00",
    sourceUrl: "https://t.me/masloplus/2742",
  },
];
